services:
  api-solid-pg:
    image: bitnami/postgresql
    container_name: api-solid-pg
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=apisolid
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  api-solid-test:
    image: bitnami/postgresql
    container_name: api-solid-test
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=apisolid_test
    ports:
      - "5433:5432"
    volumes:
      - postgres_data_test:/var/lib/postgresql/data

volumes:
  postgres_data:
  postgres_data_test: